name: Preprocessing CI

on:
  push:
    branches: [ main ]

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pandas numpy scikit-learn
      - name: Run preprocessing
        run: python preprocessing/automate_Mohamad_Rizki.py